// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoT3jG2R1YKIxseXuOmgXFkaJo84DHXTU',
    appId: '1:27008141652:web:6ac0d4b37bca722fcca0c1',
    messagingSenderId: '27008141652',
    projectId: 'chating-app-7198d',
    authDomain: 'chating-app-7198d.firebaseapp.com',
    storageBucket: 'chating-app-7198d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmYpR3ukqu45QNqAmNIyIka559y882sSE',
    appId: '1:27008141652:android:c22324d6eda39f42cca0c1',
    messagingSenderId: '27008141652',
    projectId: 'chating-app-7198d',
    storageBucket: 'chating-app-7198d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAayRcDP37uAC9Hq0JDV_cjaN5xWHAowr4',
    appId: '1:27008141652:ios:cbb30e8f2373f887cca0c1',
    messagingSenderId: '27008141652',
    projectId: 'chating-app-7198d',
    storageBucket: 'chating-app-7198d.appspot.com',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAayRcDP37uAC9Hq0JDV_cjaN5xWHAowr4',
    appId: '1:27008141652:ios:cbb30e8f2373f887cca0c1',
    messagingSenderId: '27008141652',
    projectId: 'chating-app-7198d',
    storageBucket: 'chating-app-7198d.appspot.com',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoT3jG2R1YKIxseXuOmgXFkaJo84DHXTU',
    appId: '1:27008141652:web:55d4caa25b32b697cca0c1',
    messagingSenderId: '27008141652',
    projectId: 'chating-app-7198d',
    authDomain: 'chating-app-7198d.firebaseapp.com',
    storageBucket: 'chating-app-7198d.appspot.com',
  );
}
